import 'package:im_flutter_sdk/im_flutter_sdk.dart';
export 'package:im_flutter_sdk/im_flutter_sdk.dart';

typedef Client = EMClient;
typedef ChatManager = EMChatManager;
typedef ChatEventHandle = EMChatEventHandler;
typedef GroupEventHandler = EMGroupEventHandler;
typedef RoomEventHandler = EMChatRoomEventHandler;
typedef ContactEventHandler = EMContactEventHandler;
typedef ConnectionEventHandler = EMConnectionEventHandler;
typedef MultiDeviceEventHandler = EMMultiDeviceEventHandler;
typedef Message = EMMessage;
typedef MessageReactionEvent = EMMessageReactionEvent;
typedef GroupMessageAck = EMGroupMessageAck;
typedef GroupSharedFile = EMGroupSharedFile;
typedef Group = EMGroup;
typedef MultiDevicesEvent = EMMultiDevicesEvent;
typedef ConversationType = EMConversationType;
typedef MessageEvent = ChatMessageEvent;
typedef ChatError = EMError;
typedef Conversation = EMConversation;
typedef CursorResult<T> = EMCursorResult<T>;
typedef MessageReaction = EMMessageReaction;
typedef TranslateLanguage = EMTranslateLanguage;
typedef TextMessageBody = EMTextMessageBody;
typedef GroupInfo = EMGroupInfo;
typedef GroupOptions = EMGroupOptions;
